Login and Logout tests updated
nerdyfactory/nf-react-app-template pull request #8
Opened 2021-02-02 23:50 UTC by nikolasvasconcelos

fix #5

2021-02-03 04:26 UTC, JonghunYu requested changes
@nikolasvasconcelos

Currently, you triggered the `login` function directly in the test script.
But, please add a form in the login screen add an event handler in the component and fill them and click button in the script so that we can replicate the user's behavior

2021-02-16 06:30 UTC, JonghunYu requested changes
@nikolasvasconcelos I think you didn't implement the original `login` and `logout` functions to be mocked by src/__mocks__/user.ts
Why do we need a mocked function of the functions that don't exist?

2021-02-16 06:30 UTC, JonghunYu commented on .eslintcache
> +[{"/Users/nikolasvasconcelos/Work/nf-react-app-template/src/index.tsx":"1","/Users/nikolasvasconcelos/Work/nf-react-app-template/src/reportWebVitals.ts":"2","/Users/nikolasvasconcelos/Work/nf-react-a
Please gitignore this file

2021-02-16 06:30 UTC, JonghunYu commented on src/__tests__/App.test.tsx
> +      await logout();
I think `fireEvent.click(screen.getByText('Logout'));` triggers logout under the hood so we don't need to explicitly call `logout` function in the test

2021-02-16 06:30 UTC, JonghunYu commented on src/pages/Login/index.tsx
> +    // login(user, password);
I think this should call login function

2021-02-17 02:06 UTC, nikolasvasconcelos commented
@JonghunYu Now I understood what you expected. I actually thought about letting the UI itself trigger the functions but I did not find a proper way to make it work, since those tutorials teach how to mock API only in the test file itself, and my experience with testing isn't much. I'll focus on finishing this ASAP.

2021-02-22 15:11 UTC, nikolasvasconcelos commented
@JonghunYu removed login and logout functions from testing scripts and moved to an auth hook, which is called from the user interface

2021-02-23 03:35 UTC, JonghunYu requested changes
@nikolasvasconcelos Please check the comments below

2021-02-23 03:35 UTC, JonghunYu commented on .eslintcache
> +[{"/Users/nikolasvasconcelos/Work/nf-react-app-template/src/index.tsx":"1","/Users/nikolasvasconcelos/Work/nf-react-app-template/src/reportWebVitals.ts":"2","/Users/nikolasvasconcelos/Work/nf-react-a
This file shouldn't be here. Please delete this https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-a-git-repository

2021-02-23 03:35 UTC, JonghunYu commented on src/__mocks__/user.ts
> +import { USER_TOKEN } from 'constants/utility';
Remove this file completely

2021-02-23 03:35 UTC, JonghunYu commented on src/__tests__/Api.test.ts
> +import { getUserName } from '../__mocks__/user';
I don't think we need this test file anymore

2021-02-23 03:35 UTC, JonghunYu commented on src/hooks/useAuth.ts
> +    // DEVELOPER'S IMPLEMENTATION
Add implementation here that calling `singIn` and use token from response

2021-02-23 03:35 UTC, JonghunYu commented on src/hooks/useAuth.ts
> +    // DEVELOPER'S IMPLEMENTATION
I don't think we need additional implementation or mock for the logout. Removing token from `localStorage` is enough

2021-02-23 03:42 UTC, JonghunYu commented
@nikolasvasconcelos Please think why it tries to mock request in this example https://jestjs.io/docs/en/tutorial-async

2021-02-24 00:21 UTC, JonghunYu approved these changes
@nikolasvasconcelos It looks good now. Thanks

2021-02-24 13:26 UTC, merged